Set all service versions to 0.1.0 ahead of deployment to CDC staging
lantanagroup/link-cloud pull request #342
Opened 2024-07-10 23:04 UTC by sdmcgeown

Also, make "ServiceInformation" field consistent across the appsettings.json files

2024-07-11 05:31 UTC, seanmcilvenna approved these changes
After this is released, do we merge the rc branch into master AND dev so that the version numbers increment for the other branches going forward? 

Also, you might investigate what SNAPSHOTs are in Java/Spring world... I feel like it MAY be suggested that `dev` always use -SNAPSHOT in the version but I'm not sure why and/or what the benefit is.

Regardless, these changes are approved afaic.

2024-07-11 12:31 UTC, amphillipsLGC requested changes

2024-07-11 12:31 UTC, amphillipsLGC commented on DotNet/Account/Account.csproj
You'll want to add that back as I think this service was one of the ones that were being tested to use the assembly to load the version. Just change the <Version> to 0.1.0.

You can keep the change to the appsettings.json file as it will not break anything.

2024-07-11 12:31 UTC, amphillipsLGC commented on DotNet/LinkAdmin.BFF/LinkAdmin.BFF.csproj
You'll want to add that back as I think this service was one of the ones that were being tested to use the assembly to load the version. Just change the to 0.1.0.

You can keep the change to the appsettings.json file as it will not break anything.

2024-07-12 00:03 UTC, sdmcgeown commented on DotNet/LinkAdmin.BFF/LinkAdmin.BFF.csproj
Hi Adam, I updated the .csproj files as you suggested and fixed indentation issues. Please let me know if the updated PR looks ok and I'll merge it in.

2024-07-12 17:28 UTC, amphillipsLGC approved these changes
Looks good!

2024-07-12 17:31 UTC, merged